// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		String num = (args[0]); //the num of runs

		// use camel case - the_time_to_run -> theTimeToRun
		int the_time_of_run = Integer.parseInt(num) ; //convert the num to int 
		int less = 0 ; // <0.5
		int more = 0 ; // >0.5

		for (int i = 0 ; i < the_time_of_run; i++) {
			double the_number = Math.random() ; 
			if (the_number >= 0.5) {
				less = less +1 ; 
			
			}else {
				more = more +1 ;
			}
			} 

		double ratio = 0 ;
		if (less < more) { //the if statement check which of the number is bigger
			ratio = ((double) less / (double) more) ; //ration between the less and the more
		}
		else if (less >= more) {
			ratio = ((double) more / (double) less) ; //ration between the less and the more	
		}

		System.out.println(">  0.5:  " + less + " times");
		System.out.println("<= 0.5:  " + more + " times");

		if (less == 0 || more == 0){
			System.out.println("there is no ratio");
		}else{
			System.out.println("Ratio: " + ratio );

		}
		

	//System.out.println("the number is less then 0.5: " + less);	
	//System.out.println("the number is more then o.5: " + more);	

	}
	}
// great catching for different cases 

